version: "2"
services:
  coordinator:
    image: basho/riak-ts
    ports:
      - "8087:8087"
      - "8098:8098"
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
    labels:
      - "com.basho.riak.cluster.name=${CLUSTER_NAME}"
    volumes:
      - schemas:/etc/riak/schemas
  member:
    image: basho/riak-ts
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=${CLUSTER_NAME}"
    links:
      - coordinator
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - COORDINATOR_NODE=coordinator

volumes:
  schemas: {}
