version: "2"
services:
  coordinator:
    image: basho/riak-ts
    ports:
      - "8087"
      - "8098"
    environment:
      - CLUSTER_NAME=riakts
    labels:
      - "com.basho.riak.cluster.name=riak-ts"
    volumes:
      - schemas:/etc/riak/schemas
    networks:
      - riak
  member:
    image: basho/riak-ts
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=riak-ts"
    links:
      - coordinator
    networks:
      - riak
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakts
      - COORDINATOR_NODE=coordinator

volumes:
  schemas: {}

networks:
  riak:
    external: true
