version: "2"
services:
  coordinator:
    image: basho/riak-ts
    ports:
      - "8087"
      - "8098"
    environment:
      - CLUSTER_NAME=riakts
      - CLUSTER_CONVERGENCE=${CLUSTER_CONVERGENCE}
    labels:
      - "com.basho.riak.cluster.name=riak-ts"
    volumes:
      - schemas:/etc/riak/schemas
    network_mode: bridge
  member:
    image: basho/riak-ts
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=riak-ts"
    links:
      - coordinator
    network_mode: bridge
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakts
      - COORDINATOR_NODE=coordinator
      - CLUSTER_CONVERGENCE=${CLUSTER_CONVERGENCE}

volumes:
  schemas: {}
