[core]
dcos_url = "{{dcos_url}}"
mesos_master_url = "{{mesos_master_url}}"
reporting = false
email = "dcos"
[marathon]
url = "{{marathon_url}}"
[package]
sources = ["https://github.com/basho-labs/riak-mesos-dcos-repo/archive/0.4.2.zip", "https://universe.mesosphere.com/repo"]
cache = "/var/cache/dcos"
