[core]
dcos_url = "{{dcos_url}}"
mesos_master_url = "{{mesos_master_url}}"
reporting = false
email = "dcos"
[marathon]
url = "{{marathon_url}}"
[package]
sources = [ "https://github.com/basho-labs/riak-mesos-dcos-repo/archive/0.3.1.zip", "https://github.com/mesosphere/universe/archive/version-1.x.zip",]
cache = "/var/lib/dcos/.pkgs"
